###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
    ls-tests-php:
      build:
        context: php-fpm
        args:
          TIMEZONE: Europe/Warsaw
      container_name: ls-tests-php
      working_dir: /app
      hostname: tests-php
      expose:
       - "9000"
       - "9001"
      volumes:
        - ../:/app